theme = "catppuccin_mocha"
[editor]
bufferline = "multiple"
default-line-ending = "lf"
line-number = "relative"
popup-border = "all"
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "bar"

[editor.indent-guides]
character = "â”†"
render = true
skip-levels = 1

[keys.insert]
C-s = ["normal_mode", ":w"]

[keys.normal]
C-r = ":reload"
C-s = ":w"
